project_id: 512976
api_token: "CROWDIN_PERSONAL_TOKEN"
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /docs/en/*.md
    ignore:
      - /docs/en/about.md
    translation: /docs/%two_letters_code%/%original_file_name%
